name: aosadjutant
services:
  postgres:
    image: postgres:18.1
    environment:
      POSTGRES_DB: aos_adjutant
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql
    ports:
      - 5432:5432
    logging:
      driver: local
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres", "-d", "aos_adjutant" ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s
      start_interval: 5s

  pocket-id:
    image: ghcr.io/pocket-id/pocket-id:v2.7
    restart: unless-stopped
    environment:
      APP_URL: ${AUTH_URL}
      ENCRYPTION_KEY: ${AUTH_ENCRYPTION_KEY}
      TRUST_PROXY: ${AUTH_TRUST_PROXY}
    ports:
      - 1411:1411
    healthcheck:
      test: [ "CMD", "/app/pocket-id", "healthcheck"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 30s
      start_interval: 5s
    volumes:
      - pocket-id-data:/app/data
    logging:
      driver: local

  grafana:
    image: grafana/grafana:13.0
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD}
    ports:
      - 3000:3000
    volumes:
      - grafana-data:/var/lib/grafana
      - ./infra/observability/grafana/provisioning/:/etc/grafana/provisioning/
    logging:
      driver: local

  otel-collector:
    image: otel/opentelemetry-collector:0.152.1
    environment:
      DEPLOYMENT_ENV: development
    volumes:
      - ./infra/observability/otel-collector/config.yaml:/etc/otelcol/config.yaml:ro
    ports:
      - 4317:4317
      - 4318:4318
    logging:
      driver: local

  loki:
    image: grafana/loki:3.7
    command: -config.file=/etc/loki/config.yaml
    ports:
      - 3100:3100
    volumes:
      - ./infra/observability/loki/config.yaml:/etc/loki/config.yaml:ro
      - loki-data:/loki
    logging:
      driver: local

  prometheus:
    image: prom/prometheus:v3.11.3
    command:
      - --web.enable-otlp-receiver
      - --enable-feature=exemplar-storage
      - --config.file=/etc/prometheus/config.yaml
    ports:
      - 9090:9090
    volumes:
      - ./infra/observability/prometheus/config.yaml:/etc/prometheus/config.yaml:ro
      - prometheus-data:/prometheus
    logging:
      driver: local

  tempo:
    image: grafana/tempo:2.10.5
    command: -config.file=/etc/config.yaml
    ports:
      - 3200:3200
    volumes:
      - ./infra/observability/tempo/config.yaml:/etc/config.yaml
      - tempo-data:/var/tempo
    logging:
      driver: local

volumes:
  postgres-data:
  loki-data:
  prometheus-data:
  grafana-data:
  tempo-data:
  pocket-id-data:
