name: aosadjutant
services:
  postgres:
    image: postgres:18.1
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: aos_adjutant
    volumes:
      - postgres-data:/var/lib/postgresql
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${DATABASE_USER}" ]
      interval: 5s
      timeout: 5s

  otel-collector:
    image: otel/opentelemetry-collector:0.152.1
    environment:
      DEPLOYMENT_ENV: development
    volumes:
      - ./observability/otel-collector/config.yaml:/etc/otelcol/config.yaml:ro
    ports:
      - 4317:4317
      - 4318:4318

  loki:
    image: grafana/loki:3.7
    command: -config.file=/etc/loki/config.yaml
    ports:
      - 3100:3100
    volumes:
      - ./observability/loki/config.yaml:/etc/loki/config.yaml:ro
      - loki-data:/loki

  prometheus:
    image: prom/prometheus:v3.11.3
    command:
      - --web.enable-otlp-receiver
      - --enable-feature=exemplar-storage
      - --config.file=/etc/prometheus/config.yaml
    ports:
      - 9090:9090
    volumes:
      - ./observability/prometheus/config.yaml:/etc/prometheus/config.yaml:ro
      - prometheus-data:/prometheus

  tempo:
    image: grafana/tempo:2.10.5
    command:  -config.file=/etc/config.yaml
    ports:
      - 3200:3200
    volumes:
      - ./observability/tempo/config.yaml:/etc/config.yaml
      - tempo-data:/var/tempo

  grafana:
    image: grafana/grafana:13.0
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD}
    ports:
      - 3000:3000
    volumes:
      - grafana-data:/var/lib/grafana
      - ./observability/grafana/provisioning/:/etc/grafana/provisioning/

  pocket-id:
    image: ghcr.io/pocket-id/pocket-id:v2.7
    restart: unless-stopped
    env_file: .env
    ports:
      - 1411:1411
    healthcheck:
      test: [ "CMD", "/app/pocket-id", "healthcheck"]
      interval: 1m30s
      timeout: 5s
      retries: 2
      start_period: 10s
    volumes:
      - pocket-id-data:/app/data

volumes:
  postgres-data:
  loki-data:
  prometheus-data:
  grafana-data:
  tempo-data:
  pocket-id-data:
