// <auto-generated />
using AosAdjutant.Api.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AosAdjutant.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260311170537_AddBaseUnit")]
    partial class AddBaseUnit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AbilityBattleFormation", b =>
                {
                    b.Property<int>("AbilitiesAbilityId")
                        .HasColumnType("integer")
                        .HasColumnName("ability_id");

                    b.Property<int>("BattleFormationId")
                        .HasColumnType("integer")
                        .HasColumnName("battle_formation_id");

                    b.HasKey("AbilitiesAbilityId", "BattleFormationId");

                    b.HasIndex("AbilitiesAbilityId")
                        .IsUnique();

                    b.HasIndex("BattleFormationId");

                    b.ToTable("battle_formation_ability", (string)null);
                });

            modelBuilder.Entity("AbilityFaction", b =>
                {
                    b.Property<int>("AbilitiesAbilityId")
                        .HasColumnType("integer")
                        .HasColumnName("ability_id");

                    b.Property<int>("FactionId")
                        .HasColumnType("integer")
                        .HasColumnName("faction_id");

                    b.HasKey("AbilitiesAbilityId", "FactionId");

                    b.HasIndex("AbilitiesAbilityId")
                        .IsUnique();

                    b.HasIndex("FactionId");

                    b.ToTable("faction_ability", (string)null);
                });

            modelBuilder.Entity("AbilityUnit", b =>
                {
                    b.Property<int>("AbilitiesAbilityId")
                        .HasColumnType("integer")
                        .HasColumnName("ability_id");

                    b.Property<int>("UnitId")
                        .HasColumnType("integer")
                        .HasColumnName("unit_id");

                    b.HasKey("AbilitiesAbilityId", "UnitId");

                    b.HasIndex("AbilitiesAbilityId")
                        .IsUnique();

                    b.HasIndex("UnitId");

                    b.ToTable("unit_ability", (string)null);
                });

            modelBuilder.Entity("AosAdjutant.Api.Features.Abilities.Ability", b =>
                {
                    b.Property<int>("AbilityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ability_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AbilityId"));

                    b.Property<string>("Declaration")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("declaration");

                    b.Property<string>("Effect")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("effect");

                    b.Property<bool>("IsGeneric")
                        .HasColumnType("boolean")
                        .HasColumnName("is_generic");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("name");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("phase");

                    b.Property<string>("Reaction")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("reaction");

                    b.Property<string>("Restriction")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("restriction");

                    b.Property<string>("Turn")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("turn");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("AbilityId");

                    b.ToTable("ability", (string)null);
                });

            modelBuilder.Entity("AosAdjutant.Api.Features.BattleFormations.BattleFormation", b =>
                {
                    b.Property<int>("BattleFormationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("battle_formation_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BattleFormationId"));

                    b.Property<int>("FactionId")
                        .HasColumnType("integer")
                        .HasColumnName("faction_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("name");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("BattleFormationId");

                    b.HasIndex("FactionId", "Name")
                        .IsUnique();

                    b.ToTable("battle_formation", (string)null);
                });

            modelBuilder.Entity("AosAdjutant.Api.Features.Factions.Faction", b =>
                {
                    b.Property<int>("FactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("faction_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FactionId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("name");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("FactionId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("faction", (string)null);
                });

            modelBuilder.Entity("AosAdjutant.Api.Features.Units.Unit", b =>
                {
                    b.Property<int>("UnitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("unit_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UnitId"));

                    b.Property<int>("Control")
                        .HasColumnType("integer")
                        .HasColumnName("control");

                    b.Property<int>("FactionId")
                        .HasColumnType("integer")
                        .HasColumnName("faction_id");

                    b.Property<int>("Health")
                        .HasColumnType("integer")
                        .HasColumnName("health");

                    b.Property<string>("Move")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("move");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("name");

                    b.Property<int>("Save")
                        .HasColumnType("integer")
                        .HasColumnName("save");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<int?>("WardSave")
                        .HasColumnType("integer")
                        .HasColumnName("ward_save");

                    b.HasKey("UnitId");

                    b.HasIndex("FactionId", "Name")
                        .IsUnique();

                    b.ToTable("unit", (string)null);
                });

            modelBuilder.Entity("AbilityBattleFormation", b =>
                {
                    b.HasOne("AosAdjutant.Api.Features.Abilities.Ability", null)
                        .WithMany()
                        .HasForeignKey("AbilitiesAbilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AosAdjutant.Api.Features.BattleFormations.BattleFormation", null)
                        .WithMany()
                        .HasForeignKey("BattleFormationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AbilityFaction", b =>
                {
                    b.HasOne("AosAdjutant.Api.Features.Abilities.Ability", null)
                        .WithMany()
                        .HasForeignKey("AbilitiesAbilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AosAdjutant.Api.Features.Factions.Faction", null)
                        .WithMany()
                        .HasForeignKey("FactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AbilityUnit", b =>
                {
                    b.HasOne("AosAdjutant.Api.Features.Abilities.Ability", null)
                        .WithMany()
                        .HasForeignKey("AbilitiesAbilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AosAdjutant.Api.Features.Units.Unit", null)
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AosAdjutant.Api.Features.BattleFormations.BattleFormation", b =>
                {
                    b.HasOne("AosAdjutant.Api.Features.Factions.Faction", null)
                        .WithMany("BattleFormations")
                        .HasForeignKey("FactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AosAdjutant.Api.Features.Units.Unit", b =>
                {
                    b.HasOne("AosAdjutant.Api.Features.Factions.Faction", null)
                        .WithMany("Units")
                        .HasForeignKey("FactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AosAdjutant.Api.Features.Factions.Faction", b =>
                {
                    b.Navigation("BattleFormations");

                    b.Navigation("Units");
                });
#pragma warning restore 612, 618
        }
    }
}
