// <auto-generated />
using AosAdjutant.Api.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AosAdjutant.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260425194515_AddGrandAllianceToFaction")]
    partial class AddGrandAllianceToFaction
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AbilityBattleFormation", b =>
                {
                    b.Property<int>("AbilitiesAbilityId")
                        .HasColumnType("integer")
                        .HasColumnName("ability_id");

                    b.Property<int>("BattleFormationId")
                        .HasColumnType("integer")
                        .HasColumnName("battle_formation_id");

                    b.HasKey("AbilitiesAbilityId", "BattleFormationId");

                    b.HasIndex("AbilitiesAbilityId")
                        .IsUnique();

                    b.HasIndex("BattleFormationId");

                    b.ToTable("battle_formation_ability", (string)null);
                });

            modelBuilder.Entity("AbilityFaction", b =>
                {
                    b.Property<int>("AbilitiesAbilityId")
                        .HasColumnType("integer")
                        .HasColumnName("ability_id");

                    b.Property<int>("FactionId")
                        .HasColumnType("integer")
                        .HasColumnName("faction_id");

                    b.HasKey("AbilitiesAbilityId", "FactionId");

                    b.HasIndex("AbilitiesAbilityId")
                        .IsUnique();

                    b.HasIndex("FactionId");

                    b.ToTable("faction_ability", (string)null);
                });

            modelBuilder.Entity("AbilityUnit", b =>
                {
                    b.Property<int>("AbilitiesAbilityId")
                        .HasColumnType("integer")
                        .HasColumnName("ability_id");

                    b.Property<int>("UnitId")
                        .HasColumnType("integer")
                        .HasColumnName("unit_id");

                    b.HasKey("AbilitiesAbilityId", "UnitId");

                    b.HasIndex("AbilitiesAbilityId")
                        .IsUnique();

                    b.HasIndex("UnitId");

                    b.ToTable("unit_ability", (string)null);
                });

            modelBuilder.Entity("AosAdjutant.Api.Features.Abilities.Ability", b =>
                {
                    b.Property<int>("AbilityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ability_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AbilityId"));

                    b.Property<string>("Declaration")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("declaration");

                    b.Property<string>("Effect")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("effect");

                    b.Property<bool>("IsGeneric")
                        .HasColumnType("boolean")
                        .HasColumnName("is_generic");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("name");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("phase");

                    b.Property<string>("Reaction")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("reaction");

                    b.Property<string>("Restriction")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("restriction");

                    b.Property<string>("Turn")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("turn");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("AbilityId");

                    b.ToTable("ability", (string)null);
                });

            modelBuilder.Entity("AosAdjutant.Api.Features.AttackProfiles.AttackProfile", b =>
                {
                    b.Property<int>("AttackProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("attack_profile_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AttackProfileId"));

                    b.Property<string>("Attacks")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("attacks");

                    b.Property<string>("Damage")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("damage");

                    b.Property<bool>("IsRanged")
                        .HasColumnType("boolean")
                        .HasColumnName("is_ranged");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("name");

                    b.Property<int?>("Range")
                        .HasColumnType("integer")
                        .HasColumnName("range");

                    b.Property<int?>("Rend")
                        .HasColumnType("integer")
                        .HasColumnName("rend");

                    b.Property<int>("ToHit")
                        .HasColumnType("integer")
                        .HasColumnName("to_hit");

                    b.Property<int>("ToWound")
                        .HasColumnType("integer")
                        .HasColumnName("to_wound");

                    b.Property<int>("UnitId")
                        .HasColumnType("integer")
                        .HasColumnName("unit_id");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("AttackProfileId");

                    b.HasIndex("UnitId");

                    b.HasIndex("Name", "UnitId")
                        .IsUnique();

                    b.ToTable("attack_profile", (string)null);
                });

            modelBuilder.Entity("AosAdjutant.Api.Features.BattleFormations.BattleFormation", b =>
                {
                    b.Property<int>("BattleFormationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("battle_formation_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BattleFormationId"));

                    b.Property<int>("FactionId")
                        .HasColumnType("integer")
                        .HasColumnName("faction_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("name");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("BattleFormationId");

                    b.HasIndex("FactionId", "Name")
                        .IsUnique();

                    b.ToTable("battle_formation", (string)null);
                });

            modelBuilder.Entity("AosAdjutant.Api.Features.Factions.Faction", b =>
                {
                    b.Property<int>("FactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("faction_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FactionId"));

                    b.Property<string>("GrandAlliance")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("grand_alliance");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("name");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("FactionId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("faction", (string)null);
                });

            modelBuilder.Entity("AosAdjutant.Api.Features.Units.Unit", b =>
                {
                    b.Property<int>("UnitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("unit_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UnitId"));

                    b.Property<int>("Control")
                        .HasColumnType("integer")
                        .HasColumnName("control");

                    b.Property<int>("FactionId")
                        .HasColumnType("integer")
                        .HasColumnName("faction_id");

                    b.Property<int>("Health")
                        .HasColumnType("integer")
                        .HasColumnName("health");

                    b.Property<string>("Move")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("move");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("name");

                    b.Property<int>("Save")
                        .HasColumnType("integer")
                        .HasColumnName("save");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<int?>("WardSave")
                        .HasColumnType("integer")
                        .HasColumnName("ward_save");

                    b.HasKey("UnitId");

                    b.HasIndex("FactionId", "Name")
                        .IsUnique();

                    b.ToTable("unit", (string)null);
                });

            modelBuilder.Entity("AosAdjutant.Api.Features.WeaponEffects.WeaponEffect", b =>
                {
                    b.Property<int>("WeaponEffectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("weapon_effect_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("WeaponEffectId"));

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("name");

                    b.HasKey("WeaponEffectId");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("weapon_effect", (string)null);

                    b.HasData(
                        new
                        {
                            WeaponEffectId = 1,
                            Key = "crit_2_hits",
                            Name = "Crit (2 Hits)"
                        },
                        new
                        {
                            WeaponEffectId = 2,
                            Key = "crit_auto_wound",
                            Name = "Crit (Auto-wound)"
                        },
                        new
                        {
                            WeaponEffectId = 3,
                            Key = "crit_mortal",
                            Name = "Crit (Mortal)"
                        },
                        new
                        {
                            WeaponEffectId = 4,
                            Key = "charge_1_damage",
                            Name = "Charge (+1 Damage)"
                        },
                        new
                        {
                            WeaponEffectId = 5,
                            Key = "companion",
                            Name = "Companion"
                        },
                        new
                        {
                            WeaponEffectId = 6,
                            Key = "shoot_in_combat",
                            Name = "Shoot in Combat"
                        },
                        new
                        {
                            WeaponEffectId = 7,
                            Key = "anti_monster",
                            Name = "Anti-Monster (+1 Rend)"
                        },
                        new
                        {
                            WeaponEffectId = 8,
                            Key = "anti_hero",
                            Name = "Anti-Hero (+1 Rend)"
                        },
                        new
                        {
                            WeaponEffectId = 9,
                            Key = "anti_infantry",
                            Name = "Anti-Infantry (+1 Rend)"
                        },
                        new
                        {
                            WeaponEffectId = 10,
                            Key = "anti_cavalry",
                            Name = "Anti-Cavalry (+1 Rend)"
                        },
                        new
                        {
                            WeaponEffectId = 11,
                            Key = "anti_wizard",
                            Name = "Anti-Wizard (+1 Rend)"
                        },
                        new
                        {
                            WeaponEffectId = 12,
                            Key = "anti_manifestation",
                            Name = "Anti-Manifestation (+1 Rend)"
                        },
                        new
                        {
                            WeaponEffectId = 13,
                            Key = "anti_charge",
                            Name = "Anti-Charge (+1 Rend)"
                        });
                });

            modelBuilder.Entity("AttackProfileWeaponEffect", b =>
                {
                    b.Property<int>("AttackProfileId")
                        .HasColumnType("integer")
                        .HasColumnName("attack_profile_id");

                    b.Property<int>("WeaponEffectsWeaponEffectId")
                        .HasColumnType("integer")
                        .HasColumnName("weapon_effect_id");

                    b.HasKey("AttackProfileId", "WeaponEffectsWeaponEffectId");

                    b.HasIndex("WeaponEffectsWeaponEffectId");

                    b.ToTable("attack_profile_weapon_effect", (string)null);
                });

            modelBuilder.Entity("AbilityBattleFormation", b =>
                {
                    b.HasOne("AosAdjutant.Api.Features.Abilities.Ability", null)
                        .WithMany()
                        .HasForeignKey("AbilitiesAbilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AosAdjutant.Api.Features.BattleFormations.BattleFormation", null)
                        .WithMany()
                        .HasForeignKey("BattleFormationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AbilityFaction", b =>
                {
                    b.HasOne("AosAdjutant.Api.Features.Abilities.Ability", null)
                        .WithMany()
                        .HasForeignKey("AbilitiesAbilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AosAdjutant.Api.Features.Factions.Faction", null)
                        .WithMany()
                        .HasForeignKey("FactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AbilityUnit", b =>
                {
                    b.HasOne("AosAdjutant.Api.Features.Abilities.Ability", null)
                        .WithMany()
                        .HasForeignKey("AbilitiesAbilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AosAdjutant.Api.Features.Units.Unit", null)
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AosAdjutant.Api.Features.AttackProfiles.AttackProfile", b =>
                {
                    b.HasOne("AosAdjutant.Api.Features.Units.Unit", null)
                        .WithMany("AttackProfiles")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AosAdjutant.Api.Features.BattleFormations.BattleFormation", b =>
                {
                    b.HasOne("AosAdjutant.Api.Features.Factions.Faction", null)
                        .WithMany("BattleFormations")
                        .HasForeignKey("FactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AosAdjutant.Api.Features.Units.Unit", b =>
                {
                    b.HasOne("AosAdjutant.Api.Features.Factions.Faction", null)
                        .WithMany("Units")
                        .HasForeignKey("FactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AttackProfileWeaponEffect", b =>
                {
                    b.HasOne("AosAdjutant.Api.Features.AttackProfiles.AttackProfile", null)
                        .WithMany()
                        .HasForeignKey("AttackProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AosAdjutant.Api.Features.WeaponEffects.WeaponEffect", null)
                        .WithMany()
                        .HasForeignKey("WeaponEffectsWeaponEffectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AosAdjutant.Api.Features.Factions.Faction", b =>
                {
                    b.Navigation("BattleFormations");

                    b.Navigation("Units");
                });

            modelBuilder.Entity("AosAdjutant.Api.Features.Units.Unit", b =>
                {
                    b.Navigation("AttackProfiles");
                });
#pragma warning restore 612, 618
        }
    }
}
