// <auto-generated />

using AosAdjutant.Api.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AosAdjutant.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260303182930_UpdateBattleFormationUK")]
    partial class UpdateBattleFormationUK
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AosAdjutant.Api.Features.Factions.BattleFormations.BattleFormation", b =>
                {
                    b.Property<int>("BattleFormationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("battle_formation_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BattleFormationId"));

                    b.Property<int>("FactionId")
                        .HasColumnType("integer")
                        .HasColumnName("faction_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("name");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("BattleFormationId");

                    b.HasIndex("FactionId", "Name")
                        .IsUnique();

                    b.ToTable("battle_formation", (string)null);
                });

            modelBuilder.Entity("AosAdjutant.Api.Features.Factions.Faction", b =>
                {
                    b.Property<int>("FactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("faction_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FactionId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("name");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("FactionId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("faction", (string)null);
                });

            modelBuilder.Entity("AosAdjutant.Api.Features.Factions.BattleFormations.BattleFormation", b =>
                {
                    b.HasOne("AosAdjutant.Api.Features.Factions.Faction", "Faction")
                        .WithMany("BattleFormations")
                        .HasForeignKey("FactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Faction");
                });

            modelBuilder.Entity("AosAdjutant.Api.Features.Factions.Faction", b =>
                {
                    b.Navigation("BattleFormations");
                });
#pragma warning restore 612, 618
        }
    }
}
